### ISSUE TITLE
Vite: Failed to resolve entry for package

### ISSUE THREAD

**Issue by Rysakov1986** [nicksulkers/another-svelte-router#1]
Thanks for the package! Looks very good! But i have the starter example and he doesn't work :(

```html
<!-- App.svelte -->
<script>
import {router, RouterView} from 'another-svelte-router';
import Home from "./routes/Home.svelte";
import About from "./routes/About.svelte";
import Blog from "./routes/Blog.svelte";

router.add('/', Home);
router.add('/about', About);
router.add('/blog', Blog);
</script>
<RouterView/>
```

have error:
`[plugin:vite:import-analysis] Failed to resolve entry for package "another-svelte-router". The package may have incorrect main/module/exports specified in its package.json.`

Thanks!

**Comment by nicksulkers** [comment]
It turns out the "main" attribute in the package.json was incorrect. In my own setup this was apparently not used.
I've published a new version (1.1.1) in which this is resolved. Could you try again?

**Comment by Rysakov1986** [comment]
Thanks for answer!

I create project `npm init @vitejs/app` and use simple example (from the first post), and i have error browser console: `Uncaught Error: No route matches location '/'`.

**Comment by nicksulkers** [comment]
@Rysakov1986 that error would imply that there is no route handler matching '/' (root).

Can you include your route definitions?

**Comment by Rysakov1986** [comment]
Sorry, I don't really understand, I have it like this:

```html
<!-- App.svelte -->
<script>
  import { router, RouterView } from "another-svelte-router";
  import Home from "./routes/Home.svelte";

  router.add("/", Home);
</script>

<RouterView />
```

```html
<!-- Home.svelte -->
Home
```

and have this error matching '/' (root).

**Comment by nicksulkers** [comment]
@Rysakov1986 that should work. I've set up a example project in which I'm doing exactly that. Take a look at: [another-svelte-router-example.zip](https://github.com/nicksulkers/another-svelte-router/files/6676689/another-svelte-router-example.zip)
In the example I used rollup (I started from the official [sveltejs/template](https://github.com/sveltejs/template)). I usually work with parcel. I have no Vite specific experience. If you could share your project with me, I'd be happy to take a look and see if I can find the issue.

**Comment by Rysakov1986** [comment]
@nicksulkers, with rollup no problem? it`s very good! =), i want to use another-svelte-router with vitejs.

Minimal example: [vite-another-svelte-router-example.zip](https://github.com/nicksulkers/another-svelte-router/files/6677468/vite-another-svelte-router-example.zip)

**Comment by nicksulkers** [comment]
@Rysakov1986 I've noticed the issue only happens when loading the module from the node_modules. Copying the directory to any other directory and loading it from there would work flawlessly. More specifically, the issue seems to happen or not depending on the import mapping. Rephrasing the import like the following also works:

    import {router, RouterView} from '../node_modules/another-svelte-router';

I'm guessing something goes wrong in the dependency pre-bundling or some optimization/caching mechanism of vitejs.
I'll look into this further and get back to you, for now you can use the above example as work-around.

**Comment by Rysakov1986** [comment]
@nicksulkers Thanks, to solve this problem you need to use: optimizeDeps.exclude

solve:
```html
<!-- vite.config.js -->
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
  optimizeDeps: {
    exclude: ['another-svelte-router']
  }
})

```

**Comment by nicksulkers** [comment]
@Rysakov1986 Good to hear! 😄 

I'll still look into it a bit more. It'd be great if I can make a adjustment to make it survive the vite optimizer.
It seems the router object may get instantiated multiple times causing the routes created in App.svelte to be unavailable in the RouterView.

**Comment by nicksulkers** [comment]
Having looked into this a bit more I believe to have identified the problem.

Vite merges dependency files into a single file. Except for .svelte files and in specifically this case the RouterView.svelte file.
This unedited file is imported from it's original location and imports the original router.js instead of the optimized file containing router.js. Therefor a second instance of the router object is created and the defined routes are unavailable in RouterView.svelte. 

I don't think this is something I can reasonably resolve on my end.
I can imagine this breaking more svelte components.
Ideally, .svelte files should be duplicated into the .vite cache directory and it's dependencies adjusted to the bundle file.

I think this needs to be done in the 'vite-plugin-svelte'.

Anyways, I'm closing this issue.
